packages:
  - 'submodules/crowd.dev/services/libs/*'
  - 'submodules/crowd.dev/services/archetypes/*'
  - 'workers'
  - 'workers/*'
  - 'workers/temporal/*'
  - 'frontend'
  - 'services'

overrides:
  eslint-plugin-vue: ^10.2.0
  h3: 1.15.5
  '@nuxtjs/robots': ^5.7.0
  form-data: '>=2.5.4'
