// Copyright (c) 2025 The Linux Foundation and each contributor.
// SPDX-License-Identifier: MIT

/**
 * Invalidate Nitro route cache entries matching given keywords.
 * Scans all keys in the redis cache storage and removes entries
 * whose key contains any of the provided keywords.
 *
 * Since route rule cache keys are internally generated by Nitro,
 * we match by keyword rather than exact path.
 */
export async function invalidateRouteCache(keywords: string[]) {
  const storage = useStorage('redis');

  try {
    const keys = await storage.getKeys();

    const keysToRemove = keys.filter((key) =>
      keywords.some((keyword) => key.toLowerCase().includes(keyword.toLowerCase())),
    );

    if (keysToRemove.length > 0) {
      await Promise.all(keysToRemove.map((key) => storage.removeItem(key)));
    }
  } catch (error) {
    // Cache invalidation is best-effort — don't break the request if it fails
    console.warn('Failed to invalidate route cache:', error);
  }
}
