export const geoMapCountries = [
  { name: 'Afghanistan', value: 0, emoji: '🇦🇫' },
  { name: 'Angola', value: 0, emoji: '🇦🇴' },
  { name: 'Albania', value: 0, emoji: '🇦🇱' },
  { name: 'United Arab Emirates', value: 0, emoji: '🇦🇪' },
  { name: 'Argentina', value: 0, emoji: '🇦🇷' },
  { name: 'Armenia', value: 0, emoji: '🇦🇲' },
  { name: 'French Southern and Antarctic Lands', value: 0, emoji: '🇹🇫' },
  { name: 'Australia', value: 0, emoji: '🇦🇺' },
  { name: 'Austria', value: 0, emoji: '🇦🇹' },
  { name: 'Azerbaijan', value: 0, emoji: '🇦🇿' },
  { name: 'Burundi', value: 0, emoji: '🇧🇮' },
  { name: 'Belgium', value: 0, emoji: '🇧🇪' },
  { name: 'Benin', value: 0, emoji: '🇧🇯' },
  { name: 'Burkina Faso', value: 0, emoji: '🇧🇫' },
  { name: 'Bangladesh', value: 0, emoji: '🇧🇩' },
  { name: 'Bulgaria', value: 0, emoji: '🇧🇬' },
  { name: 'The Bahamas', value: 0, emoji: '🇧🇸' },
  { name: 'Bosnia and Herzegovina', value: 0, emoji: '🇧🇦' },
  { name: 'Belarus', value: 0, emoji: '🇧🇾' },
  { name: 'Belize', value: 0, emoji: '🇧🇿' },
  { name: 'Bermuda', value: 0, emoji: '🇧🇲' },
  { name: 'Bolivia', value: 0, emoji: '🇧🇴' },
  { name: 'Brazil', value: 0, emoji: '🇧🇷' },
  { name: 'Brunei', value: 0, emoji: '🇧🇳' },
  { name: 'Bhutan', value: 0, emoji: '🇧🇹' },
  { name: 'Botswana', value: 0, emoji: '🇧🇼' },
  { name: 'Central African Republic', value: 0, emoji: '🇨🇫' },
  { name: 'Canada', value: 0, emoji: '🇨🇦' },
  { name: 'Switzerland', value: 0, emoji: '🇨🇭' },
  { name: 'Chile', value: 0, emoji: '🇨🇱' },
  { name: 'China', value: 0, emoji: '🇨🇳' },
  { name: 'Ivory Coast', value: 0, emoji: '🇨🇮' },
  { name: 'Cameroon', value: 0, emoji: '🇨🇲' },
  { name: 'Democratic Republic of the Congo', value: 0, emoji: '🇨🇩' },
  { name: 'Republic of the Congo', value: 0, emoji: '🇨🇬' },
  { name: 'Colombia', value: 0, emoji: '🇨🇴' },
  { name: 'Costa Rica', value: 0, emoji: '🇨🇷' },
  { name: 'Cuba', value: 0, emoji: '🇨🇺' },
  { name: 'Northern Cyprus', value: 0, emoji: '🇨🇾' },
  { name: 'Cyprus', value: 0, emoji: '🇨🇾' },
  { name: 'Czech Republic', value: 0, emoji: '🇨🇿' },
  { name: 'Germany', value: 0, emoji: '🇩🇪' },
  { name: 'Djibouti', value: 0, emoji: '🇩🇯' },
  { name: 'Denmark', value: 0, emoji: '🇩🇰' },
  { name: 'Dominican Republic', value: 0, emoji: '🇩🇴' },
  { name: 'Algeria', value: 0, emoji: '🇩🇿' },
  { name: 'Ecuador', value: 0, emoji: '🇪🇨' },
  { name: 'Egypt', value: 0, emoji: '🇪🇬' },
  { name: 'Eritrea', value: 0, emoji: '🇪🇷' },
  { name: 'Spain', value: 0, emoji: '🇪🇸' },
  { name: 'Estonia', value: 0, emoji: '🇪🇪' },
  { name: 'Ethiopia', value: 0, emoji: '🇪🇹' },
  { name: 'Finland', value: 0, emoji: '🇫🇮' },
  { name: 'Fiji', value: 0, emoji: '🇫🇯' },
  { name: 'Falkland Islands', value: 0, emoji: '🇫🇰' },
  { name: 'France', value: 0, emoji: '🇫🇷' },
  { name: 'Gabon', value: 0, emoji: '🇬🇦' },
  { name: 'United Kingdom', value: 0, emoji: '🇬🇧' },
  { name: 'Georgia', value: 0, emoji: '🇬🇪' },
  { name: 'Ghana', value: 0, emoji: '🇬🇭' },
  { name: 'Guinea', value: 0, emoji: '🇬🇳' },
  { name: 'Gambia', value: 0, emoji: '🇬🇲' },
  { name: 'Guinea Bissau', value: 0, emoji: '🇬🇼' },
  { name: 'Equatorial Guinea', value: 0, emoji: '🇬🇶' },
  { name: 'Greece', value: 0, emoji: '🇬🇷' },
  { name: 'Greenland', value: 0, emoji: '🇬🇱' },
  { name: 'Guatemala', value: 0, emoji: '🇬🇹' },
  { name: 'French Guiana', value: 0, emoji: '🇬🇫' },
  { name: 'Guyana', value: 0, emoji: '🇬🇾' },
  { name: 'Honduras', value: 0, emoji: '🇭🇳' },
  { name: 'Croatia', value: 0, emoji: '🇭🇷' },
  { name: 'Haiti', value: 0, emoji: '🇭🇹' },
  { name: 'Hungary', value: 0, emoji: '🇭🇺' },
  { name: 'Indonesia', value: 0, emoji: '🇮🇩' },
  { name: 'India', value: 0, emoji: '🇮🇳' },
  { name: 'Ireland', value: 0, emoji: '🇮🇪' },
  { name: 'Iran', value: 0, emoji: '🇮🇷' },
  { name: 'Iraq', value: 0, emoji: '🇮🇶' },
  { name: 'Iceland', value: 0, emoji: '🇮🇸' },
  { name: 'Israel', value: 0, emoji: '🇮🇱' },
  { name: 'Italy', value: 0, emoji: '🇮🇹' },
  { name: 'Jamaica', value: 0, emoji: '🇯🇲' },
  { name: 'Jordan', value: 0, emoji: '🇯🇴' },
  { name: 'Japan', value: 0, emoji: '🇯🇵' },
  { name: 'Kazakhstan', value: 0, emoji: '🇰🇿' },
  { name: 'Kenya', value: 0, emoji: '🇰🇪' },
  { name: 'Kyrgyzstan', value: 0, emoji: '🇰🇬' },
  { name: 'Cambodia', value: 0, emoji: '🇰🇭' },
  { name: 'South Korea', value: 0, emoji: '🇰🇷' },
  { name: 'Kosovo', value: 0, emoji: '🇽🇰' },
  { name: 'Kuwait', value: 0, emoji: '🇰🇼' },
  { name: 'Laos', value: 0, emoji: '🇱🇦' },
  { name: 'Lebanon', value: 0, emoji: '🇱🇧' },
  { name: 'Liberia', value: 0, emoji: '🇱🇷' },
  { name: 'Libya', value: 0, emoji: '🇱🇾' },
  { name: 'Sri Lanka', value: 0, emoji: '🇱🇰' },
  { name: 'Lesotho', value: 0, emoji: '🇱🇸' },
  { name: 'Lithuania', value: 0, emoji: '🇱🇹' },
  { name: 'Luxembourg', value: 0, emoji: '🇱🇺' },
  { name: 'Latvia', value: 0, emoji: '🇱🇻' },
  { name: 'Morocco', value: 0, emoji: '🇲🇦' },
  { name: 'Moldova', value: 0, emoji: '🇲🇩' },
  { name: 'Madagascar', value: 0, emoji: '🇲🇬' },
  { name: 'Mexico', value: 0, emoji: '🇲🇽' },
  { name: 'Macedonia', value: 0, emoji: '🇲🇰' },
  { name: 'Mali', value: 0, emoji: '🇲🇱' },
  { name: 'Myanmar', value: 0, emoji: '🇲🇲' },
  { name: 'Montenegro', value: 0, emoji: '🇲🇪' },
  { name: 'Mongolia', value: 0, emoji: '🇲🇳' },
  { name: 'Mozambique', value: 0, emoji: '🇲🇿' },
  { name: 'Mauritania', value: 0, emoji: '🇲🇷' },
  { name: 'Malawi', value: 0, emoji: '🇲🇼' },
  { name: 'Malaysia', value: 0, emoji: '🇲🇾' },
  { name: 'Namibia', value: 0, emoji: '🇳🇦' },
  { name: 'New Caledonia', value: 0, emoji: '🇳🇨' },
  { name: 'Niger', value: 0, emoji: '🇳🇪' },
  { name: 'Nigeria', value: 0, emoji: '🇳🇬' },
  { name: 'Nicaragua', value: 0, emoji: '🇳🇮' },
  { name: 'Netherlands', value: 0, emoji: '🇳🇱' },
  { name: 'Norway', value: 0, emoji: '🇳🇴' },
  { name: 'Nepal', value: 0, emoji: '🇳🇵' },
  { name: 'New Zealand', value: 0, emoji: '🇳🇿' },
  { name: 'Oman', value: 0, emoji: '🇴🇲' },
  { name: 'Pakistan', value: 0, emoji: '🇵🇰' },
  { name: 'Panama', value: 0, emoji: '🇵🇦' },
  { name: 'Peru', value: 0, emoji: '🇵🇪' },
  { name: 'Philippines', value: 0, emoji: '🇵🇭' },
  { name: 'Papua New Guinea', value: 0, emoji: '🇵🇬' },
  { name: 'Poland', value: 0, emoji: '🇵🇱' },
  { name: 'Puerto Rico', value: 0, emoji: '🇵🇷' },
  { name: 'North Korea', value: 0, emoji: '🇰🇵' },
  { name: 'Portugal', value: 0, emoji: '🇵🇹' },
  { name: 'Paraguay', value: 0, emoji: '🇵🇾' },
  { name: 'Qatar', value: 0, emoji: '🇶🇦' },
  { name: 'Romania', value: 0, emoji: '🇷🇴' },
  { name: 'Russia', value: 0, emoji: '🇷🇺' },
  { name: 'Rwanda', value: 0, emoji: '🇷🇼' },
  { name: 'Western Sahara', value: 0, emoji: '🇪🇭' },
  { name: 'Saudi Arabia', value: 0, emoji: '🇸🇦' },
  { name: 'Sudan', value: 0, emoji: '🇸🇩' },
  { name: 'South Sudan', value: 0, emoji: '🇸🇸' },
  { name: 'Senegal', value: 0, emoji: '🇸🇳' },
  { name: 'Solomon Islands', value: 0, emoji: '🇸🇧' },
  { name: 'Sierra Leone', value: 0, emoji: '🇸🇱' },
  { name: 'El Salvador', value: 0, emoji: '🇸🇻' },
  { name: 'Somaliland', value: 0, emoji: '🇸🇴' },
  { name: 'Somalia', value: 0, emoji: '🇸🇴' },
  { name: 'Republic of Serbia', value: 0, emoji: '🇷🇸' },
  { name: 'Suriname', value: 0, emoji: '🇸🇷' },
  { name: 'Slovakia', value: 0, emoji: '🇸🇰' },
  { name: 'Slovenia', value: 0, emoji: '🇸🇮' },
  { name: 'Sweden', value: 0, emoji: '🇸🇪' },
  { name: 'Swaziland', value: 0, emoji: '🇸🇿' },
  { name: 'Syria', value: 0, emoji: '🇸🇾' },
  { name: 'Chad', value: 0, emoji: '🇹🇩' },
  { name: 'Togo', value: 0, emoji: '🇹🇬' },
  { name: 'Thailand', value: 0, emoji: '🇹🇭' },
  { name: 'Tajikistan', value: 0, emoji: '🇹🇯' },
  { name: 'Turkmenistan', value: 0, emoji: '🇹🇲' },
  { name: 'East Timor', value: 0, emoji: '🇹🇱' },
  { name: 'Trinidad and Tobago', value: 0, emoji: '🇹🇹' },
  { name: 'Tunisia', value: 0, emoji: '🇹🇳' },
  { name: 'Turkey', value: 0, emoji: '🇹🇷' },
  { name: 'United Republic of Tanzania', value: 0, emoji: '🇹🇿' },
  { name: 'Uganda', value: 0, emoji: '🇺🇬' },
  { name: 'Ukraine', value: 0, emoji: '🇺🇦' },
  { name: 'Uruguay', value: 0, emoji: '🇺🇾' },
  { name: 'United States of America', value: 0, emoji: '🇺🇸' },
  { name: 'Uzbekistan', value: 0, emoji: '🇺🇿' },
  { name: 'Venezuela', value: 0, emoji: '🇻🇪' },
  { name: 'Vietnam', value: 0, emoji: '🇻🇳' },
  { name: 'Vanuatu', value: 0, emoji: '🇻🇺' },
  { name: 'West Bank', value: 0, emoji: '🇵🇸' },
  { name: 'Yemen', value: 0, emoji: '🇾🇪' },
  { name: 'South Africa', value: 0, emoji: '🇿🇦' },
  { name: 'Zambia', value: 0, emoji: '🇿🇲' },
  { name: 'Zimbabwe', value: 0, emoji: '🇿🇼' }
];
