version: '3.1'

x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: package-downloads-worker
  INSIGHTS_TEMPORAL_TASKQUEUE: package-downloads
  SHELL: /bin/sh

services:
  package-downloads-worker:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.package_downloads_worker
    command: 'pnpm run start'
    working_dir: /usr/insights/app/workers/package_downloads_worker
    env_file:
      - ../../.env.dist.local
      - ../../.env.dist.composed
      - ../../.env.override.local
      - ../../.env.override.composed
    environment:
      <<: *env-args
    restart: always
    networks:
      - insights-bridge

  package-downloads-worker-dev:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.package_downloads_worker
    command: 'pnpm run dev'
    working_dir: /usr/insights/app/workers/package_downloads_worker
    # user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../.env.dist.local
      - ../../.env.dist.composed
      - ../../.env.override.local
      - ../../.env.override.composed
    environment:
      <<: *env-args
    hostname: package-downloads-worker
    networks:
      - insights-bridge
    volumes:
      - ../../submodules/crowd.dev/services/libs/common/src:/usr/insights/app/services/libs/common/src
      - ../../submodules/crowd.dev/services/libs/common_services/src:/usr/insights/app/services/libs/common_services/src
      - ../../submodules/crowd.dev/services/libs/data-access-layer/src:/usr/insights/app/services/libs/data-access-layer/src
      - ../../submodules/crowd.dev/services/libs/database/src:/usr/insights/app/services/libs/database/src
      - ../../submodules/crowd.dev/services/libs/integrations/src:/usr/insights/app/services/libs/integrations/src
      - ../../submodules/crowd.dev/services/libs/logging/src:/usr/insights/app/services/libs/logging/src
      - ../../submodules/crowd.dev/services/libs/temporal/src:/usr/insights/app/services/libs/temporal/src
      - ../../submodules/crowd.dev/services/libs/types/src:/usr/insights/app/services/libs/types/src
      - ../../workers/package_downloads_worker/src:/usr/insights/app/workers/package_downloads_worker/src

networks:
  insights-bridge:
    external: true
