name: Insights docker image builder
description: Builds and pushes insights docker image with caching

inputs:
  app-env:
    description: The APP_ENV to pass as a build argument
    required: false
    default: production
  dockerfile:
    description: Path to the Dockerfile
    required: true
  image-name:
    description: Image name (e.g. insights-app, package-downloads-worker)
    required: true
  build-args:
    description: Extra build args (newline-separated KEY=VALUE)
    required: false
    default: ''

outputs:
  image:
    description: Image that was built
    value: ${{ steps.tag-generator.outputs.IMAGE_TAG }}

runs:
  using: composite
  steps:
    - name: Generate image tag
      shell: bash
      id: tag-generator
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
        IMAGE_VERSION="${SHORT_SHA}.${{ github.run_attempt }}"
        IMAGE_TAG="sjc.ocir.io/axbydjxa5zuh/${{ inputs.image-name }}:${IMAGE_VERSION}"
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Oracle Container Registry
      uses: docker/login-action@v3
      with:
        registry: sjc.ocir.io
        username: ${{ env.ORACLE_DOCKER_USERNAME }}
        password: ${{ env.ORACLE_DOCKER_PASSWORD }}

    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.tag-generator.outputs.IMAGE_TAG }}
        build-args: |
          APP_ENV=${{ inputs.app-env }}
          ${{ inputs.build-args }}
        no-cache: true
        provenance: false
