name: Deploy to Oracle
description: Changes

runs:
  using: composite
  steps:
    - name: Configure Oracle Cloud CLI
      run: |
        mkdir -p ~/.oci
        echo "${{ env.ORACLE_KEY }}" | base64 --decode > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ env.ORACLE_USER }}" >> ~/.oci/config
        echo "fingerprint=${{ env.ORACLE_FINGERPRINT }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
        echo "tenancy=${{ env.ORACLE_TENANT }}" >> ~/.oci/config
        echo "region=${{ env.ORACLE_REGION }}" >> ~/.oci/config
        echo "pass_phrase=${{ env.ORACLE_KEY_PASSPHRASE }}" >> ~/.oci/config
        chmod 600 ~/.oci/config

    - name: Verify OCI CLI Configuration
      run: |
        oci os ns get --config-file ~/.oci/config || cat ~/.oci/config

    - name: Get Cluster Kubeconfig
      run: |
        oci ce cluster create-kubeconfig --cluster-id ${{ env.ORACLE_CLUSTER }} --file ${{ env.KUBECONFIG_PATH }} --region ${{ env.ORACLE_REGION }} --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT --overwrite

