services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    command: -c 'max_connections=300' -c 'wal_level=logical' -c 'max_replication_slots=15'
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=insights
    ports:
      - 5435:5432
    volumes:
      - insights-pgdata-dev:/var/lib/postgresql/data
    shm_size: 1gb
    networks:
      - insights-bridge
  
  temporal:
    build:
      context: scaffold/temporal
    restart: unless-stopped
    ports:
      - '7233:7233'
      - '8233:8233'
    networks:
      - insights-bridge

networks:
  insights-bridge:
    external: true

volumes:
  insights-pgdata-dev:
