// Copyright (c) 2025 The Linux Foundation and each contributor.
// SPDX-License-Identifier: MIT
export enum LfxRoutes {
  HOME = '/',
  EXPLORE = 'index',
  OPENSOURCEINDEX = 'open-source-index',
  LEADERBOARDS = 'leaderboards',
  OPENSOURCEINDEX_GROUP = 'open-source-index-group-slug',
  OPENSOURCEINDEX_CATEGORY = 'open-source-index-category-slug',
  COLLECTIONS = 'collection',
  COLLECTION = 'collection-slug',
  PROJECTS = 'project',
  PROJECT = 'project-slug',
  PROJECT_CONTRIBUTORS = 'project-slug-contributors',
  PROJECT_POPULARITY = 'project-slug-popularity',
  PROJECT_DEVELOPMENT = 'project-slug-development',
  PROJECT_SECURITY = 'project-slug-security',
  REPOSITORY = 'project-slug-repository-name',
  REPOSITORY_CONTRIBUTORS = 'project-slug-repository-name-contributors',
  REPOSITORY_POPULARITY = 'project-slug-repository-name-popularity',
  REPOSITORY_DEVELOPMENT = 'project-slug-repository-name-development',
  REPOSITORY_SECURITY = 'project-slug-repository-name-security',
  REPOSITORY_GROUP = 'project-slug-repository-group-groupSlug',
  REPOSITORY_GROUP_CONTRIBUTORS = 'project-slug-repository-group-groupSlug-contributors',
  REPOSITORY_GROUP_POPULARITY = 'project-slug-repository-group-groupSlug-popularity',
  REPOSITORY_GROUP_DEVELOPMENT = 'project-slug-repository-group-groupSlug-development',
  REPOSITORY_GROUP_SECURITY = 'project-slug-repository-group-groupSlug-security',
}
