export enum LfxRoutes {
    // EXPLORE = 'index',
    OPENSOURCEINDEX = 'open-source-index',
    COLLECTIONS = 'index',
    COLLECTION = 'collection-slug',
    PROJECTS = 'project',
    PROJECT = 'project-slug',
    // PROJECT_CONTRIBUTORS = 'project-slug-contributors',
    PROJECT_POPULARITY = 'project-slug-popularity',
    PROJECT_DEVELOPMENT = 'project-slug-development',
    // PROJECT_SECURITY = 'project-slug-security',
    REPOSITORY = 'project-slug-repository-name',
    // REPOSITORY_CONTRIBUTORS = 'project-slug-repository-name-contributors',
    REPOSITORY_POPULARITY = 'project-slug-repository-name-popularity',
    REPOSITORY_DEVELOPMENT = 'project-slug-repository-name-development',
    // REPOSITORY_SECURITY = 'project-slug-repository-name-security',
}
