// Copyright (c) 2025 The Linux Foundation and each contributor.
// SPDX-License-Identifier: MIT
import Forks from './forks.vue'
import type { WidgetConfig } from '~/components/modules/widget/config/widget.config'

const forks: WidgetConfig = {
  key: 'forks',
  name: 'Forks',
  description: () => 'New forks (copies) of the project repositories during the selected time period.',
  learnMoreLink: `/docs/metrics/popularity#forks`,
  component: Forks,
  defaultValue: {
    activeTab: 'new',
  },
  share: true,
  embed: true,
  snapshot: true,
  benchmark: {
    title: 'GitHub Forks',
    showOnOverview: true,
    isVisible: () => true,
    points: {
      0: {
        type: 'negative',
        description: '{value} forks',
        text: `This project has very few forks, indicating minimal 
				community engagement. Keep in mind that fork counts may 
				not fully capture real development interest and
				can be influenced by various factors.`,
      },
      1: {
        type: 'negative',
        description: '{value} forks',
        text: `This project has few forks, suggesting a small degree 
				of interest in adapting or building upon its code. However, 
				fork numbers can sometimes be affected by one-off events or campaigns.`,
      },
      2: {
        type: 'warning',
        description: '{value} forks',
        text: `This project demonstrates moderate forking activity, 
				reflecting some interest in extending the project. 
				Remember that fork counts should be interpreted 
				alongside other indicators of community involvement.`,
      },
      3: {
        type: 'warning',
        description: '{value} forks',
        text: `This project has decent forking activity, 
				indicating a good level of community participation. 
				Still, fork numbers can be susceptible to short-term trends 
				and should be cross-referenced with other metrics.`,
      },
      4: {
        type: 'positive',
        description: '{value} forks',
        text: `This project has strong forking activity, 
				showcasing significant community interest 
				and a tendency to innovate. However, it's important 
				to note that forks can sometimes be generated by 
				automated or bulk actions.`,
      },
      5: {
        type: 'positive',
        description: '{value} forks',
        text: `This project has exceptional forking activity, 
				suggesting widespread influence and robust engagement. 
				While impressive, fork counts can occasionally be artificially inflated, 
				so consider them in context with additional metrics.`,
      },
    },
  },
}

export default forks
