name: License Header Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # or whatever version you use

      - name: Install dependencies (if needed)
        run: npm ci || true  # Use this if your script requires deps, else skip

      - name: Run license check
        run: node scripts/check-license.js